spring.application.name=review-orchestrator-service

# Server
server.port=8080

#Kafka
kafka.bootstrap-servers=localhost:9092
kafka.topics.pr-events=pr-events
kafka.topics.code-fetch-requests=code-fetch-requests

# Logging
logging.level.root=INFO
logging.level.com.codereview.webhook=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Jackson (optional strict parsing)
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=true
spring.jackson.mapper.DEFAULT_VIEW_INCLUSION=false

# Actuator (optional)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


